config/routes.rb
Rails.application.routes.draw do
  resources :booking_equipments
  resources :equipment
  resources :special_offers
  resources :reviews
  resources :facility_availabilities
  resources :membership_plans
  resources :payments
  resources :bookings
  resources :facilities
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/special_offer.rb
class SpecialOffer < ApplicationRecord
  belongs_to :facility
end

app/controllers/special_offers_controller.rb
class SpecialOffersController < ApplicationController
  before_action :set_special_offer, only: %i[ show edit update destroy ]

  # GET /special_offers or /special_offers.json
  def index
    @special_offers = SpecialOffer.all
  end

  # GET /special_offers/1 or /special_offers/1.json
  def show
  end

  # GET /special_offers/new
  def new
    @special_offer = SpecialOffer.new
  end

  # GET /special_offers/1/edit
  def edit
  end

  # POST /special_offers or /special_offers.json
  def create
    @special_offer = SpecialOffer.new(special_offer_params)

    respond_to do |format|
      if @special_offer.save
        format.html { redirect_to @special_offer, notice: "Special offer was successfully created." }
        format.json { render :show, status: :created, location: @special_offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @special_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /special_offers/1 or /special_offers/1.json
  def update
    respond_to do |format|
      if @special_offer.update(special_offer_params)
        format.html { redirect_to @special_offer, notice: "Special offer was successfully updated." }
        format.json { render :show, status: :ok, location: @special_offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @special_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /special_offers/1 or /special_offers/1.json
  def destroy
    @special_offer.destroy!

    respond_to do |format|
      format.html { redirect_to special_offers_path, status: :see_other, notice: "Special offer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_special_offer
      @special_offer = SpecialOffer.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def special_offer_params
      params.expect(special_offer: [ :name, :description, :discount_percentage, :start_date, :end_date, :facility_id, :min_hours, :code, :is_active ])
    end
end

app/helpers/special_offers_helper.rb
module SpecialOffersHelper
end

app/views/special_offers/_form.html.erb
<%= form_with(model: special_offer, class: "contents") do |form| %>
  <% if special_offer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(special_offer.errors.count, "error") %> prohibited this special_offer from being saved:</h2>

      <ul class="list-disc ml-6">
        <% special_offer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": special_offer.errors[:name].none?, "border-red-400 focus:outline-red-600": special_offer.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": special_offer.errors[:description].none?, "border-red-400 focus:outline-red-600": special_offer.errors[:description].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :discount_percentage %>
    <%= form.text_field :discount_percentage, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": special_offer.errors[:discount_percentage].none?, "border-red-400 focus:outline-red-600": special_offer.errors[:discount_percentage].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": special_offer.errors[:start_date].none?, "border-red-400 focus:outline-red-600": special_offer.errors[:start_date].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": special_offer.errors[:end_date].none?, "border-red-400 focus:outline-red-600": special_offer.errors[:end_date].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :facility_id %>
    <%= form.text_field :facility_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": special_offer.errors[:facility_id].none?, "border-red-400 focus:outline-red-600": special_offer.errors[:facility_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :min_hours %>
    <%= form.number_field :min_hours, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": special_offer.errors[:min_hours].none?, "border-red-400 focus:outline-red-600": special_offer.errors[:min_hours].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :code %>
    <%= form.text_field :code, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": special_offer.errors[:code].none?, "border-red-400 focus:outline-red-600": special_offer.errors[:code].any?}] %>
  </div>

  <div class="my-5 flex items-center gap-2">
    <%= form.label :is_active %>
    <%= form.checkbox :is_active, class: ["block shadow-sm rounded-md border order-first h-5 w-5", {"border-gray-400 focus:outline-blue-600": special_offer.errors[:is_active].none?, "border-red-400 focus:outline-red-600": special_offer.errors[:is_active].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/special_offers/_special_offer.html.erb
<div id="<%= dom_id special_offer %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= special_offer.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Description:</strong>
    <%= special_offer.description %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Discount percentage:</strong>
    <%= special_offer.discount_percentage %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Start date:</strong>
    <%= special_offer.start_date %>
  </div>
  <div>
    <strong class="block font-medium mb-1">End date:</strong>
    <%= special_offer.end_date %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Facility:</strong>
    <%= special_offer.facility_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Min hours:</strong>
    <%= special_offer.min_hours %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Code:</strong>
    <%= special_offer.code %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Is active:</strong>
    <%= special_offer.is_active? ? "Yes" : "No" %>
  </div>
</div>

app/views/special_offers/edit.html.erb
<% content_for :title, "Editing special offer" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing special offer</h1>

  <%= render "form", special_offer: @special_offer %>

  <%= link_to "Show this special offer", @special_offer, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to special offers", special_offers_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/special_offers/index.html.erb
<% content_for :title, "Special offers" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Special offers</h1>
    <%= link_to "New special offer", new_special_offer_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="special_offers" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @special_offers.any? %>
      <% @special_offers.each do |special_offer| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render special_offer %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", special_offer, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_special_offer_path(special_offer), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", special_offer, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No special offers found.</p>
    <% end %>
  </div>
</div>

app/views/special_offers/new.html.erb
<% content_for :title, "New special offer" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New special offer</h1>

  <%= render "form", special_offer: @special_offer %>

  <%= link_to "Back to special offers", special_offers_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/special_offers/show.html.erb
<% content_for :title, "Showing special offer" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing special offer</h1>

  <%= render @special_offer %>

  <%= link_to "Edit this special offer", edit_special_offer_path(@special_offer), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to special offers", special_offers_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this special offer", @special_offer, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>