config/routes.rb
Rails.application.routes.draw do
  resources :booking_equipments
  resources :equipment
  resources :special_offers
  resources :reviews
  resources :facility_availabilities
  resources :membership_plans
  resources :payments
  resources :bookings
  resources :facilities
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :facility
end

app/models/booking_equipment.rb
class BookingEquipment < ApplicationRecord
  belongs_to :booking
  belongs_to :equipment
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
end

app/models/facility.rb
class Facility < ApplicationRecord
end

app/models/facility_availability.rb
class FacilityAvailability < ApplicationRecord
  belongs_to :facility
end

app/models/membership_plan.rb
class MembershipPlan < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :booking
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
  belongs_to :facility
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/special_offer.rb
class SpecialOffer < ApplicationRecord
  belongs_to :facility
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :first_name, :last_name, presence: true
  validates :password, length: { minimum: 6 }, if: -> { new_record? || !password.nil? }

  has_many :sessions, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :user_memberships, dependent: :destroy
  has_many :membership_plans, through: :user_memberships
  has_many :reviews, dependent: :destroy
  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/booking_equipments_controller.rb
class BookingEquipmentsController < ApplicationController
  before_action :set_booking_equipment, only: %i[ show edit update destroy ]

  # GET /booking_equipments or /booking_equipments.json
  def index
    @booking_equipments = BookingEquipment.all
  end

  # GET /booking_equipments/1 or /booking_equipments/1.json
  def show
  end

  # GET /booking_equipments/new
  def new
    @booking_equipment = BookingEquipment.new
  end

  # GET /booking_equipments/1/edit
  def edit
  end

  # POST /booking_equipments or /booking_equipments.json
  def create
    @booking_equipment = BookingEquipment.new(booking_equipment_params)

    respond_to do |format|
      if @booking_equipment.save
        format.html { redirect_to @booking_equipment, notice: "Booking equipment was successfully created." }
        format.json { render :show, status: :created, location: @booking_equipment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking_equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /booking_equipments/1 or /booking_equipments/1.json
  def update
    respond_to do |format|
      if @booking_equipment.update(booking_equipment_params)
        format.html { redirect_to @booking_equipment, notice: "Booking equipment was successfully updated." }
        format.json { render :show, status: :ok, location: @booking_equipment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking_equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /booking_equipments/1 or /booking_equipments/1.json
  def destroy
    @booking_equipment.destroy!

    respond_to do |format|
      format.html { redirect_to booking_equipments_path, status: :see_other, notice: "Booking equipment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking_equipment
      @booking_equipment = BookingEquipment.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def booking_equipment_params
      params.expect(booking_equipment: [ :booking_id, :equipment_id, :quantity, :price_per_unit, :total_price ])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy!

    respond_to do |format|
      format.html { redirect_to reviews_path, status: :see_other, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.expect(review: [ :booking_id, :user_id, :facility_id, :rating, :comment ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_equipments_helper.rb
module BookingEquipmentsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/special_offers_helper.rb
module SpecialOffersHelper
end

app/views/booking_equipments/_booking_equipment.html.erb
<div id="<%= dom_id booking_equipment %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Booking:</strong>
    <%= booking_equipment.booking_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Equipment:</strong>
    <%= booking_equipment.equipment_id %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Quantity:</strong>
    <%= booking_equipment.quantity %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Price per unit:</strong>
    <%= booking_equipment.price_per_unit %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Total price:</strong>
    <%= booking_equipment.total_price %>
  </div>
</div>

app/views/booking_equipments/_form.html.erb
<%= form_with(model: booking_equipment, class: "contents") do |form| %>
  <% if booking_equipment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(booking_equipment.errors.count, "error") %> prohibited this booking_equipment from being saved:</h2>

      <ul class="list-disc ml-6">
        <% booking_equipment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :booking_id %>
    <%= form.text_field :booking_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": booking_equipment.errors[:booking_id].none?, "border-red-400 focus:outline-red-600": booking_equipment.errors[:booking_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :equipment_id %>
    <%= form.text_field :equipment_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": booking_equipment.errors[:equipment_id].none?, "border-red-400 focus:outline-red-600": booking_equipment.errors[:equipment_id].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": booking_equipment.errors[:quantity].none?, "border-red-400 focus:outline-red-600": booking_equipment.errors[:quantity].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :price_per_unit %>
    <%= form.text_field :price_per_unit, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": booking_equipment.errors[:price_per_unit].none?, "border-red-400 focus:outline-red-600": booking_equipment.errors[:price_per_unit].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :total_price %>
    <%= form.text_field :total_price, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": booking_equipment.errors[:total_price].none?, "border-red-400 focus:outline-red-600": booking_equipment.errors[:total_price].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/booking_equipments/edit.html.erb
<% content_for :title, "Editing booking equipment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing booking equipment</h1>

  <%= render "form", booking_equipment: @booking_equipment %>

  <%= link_to "Show this booking equipment", @booking_equipment, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to booking equipment", booking_equipments_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/booking_equipments/index.html.erb
<% content_for :title, "Booking equipment" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Booking equipment</h1>
    <%= link_to "New booking equipment", new_booking_equipment_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="booking_equipments" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @booking_equipments.any? %>
      <% @booking_equipments.each do |booking_equipment| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render booking_equipment %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", booking_equipment, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_booking_equipment_path(booking_equipment), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", booking_equipment, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No booking equipment found.</p>
    <% end %>
  </div>
</div>

app/views/booking_equipments/new.html.erb
<% content_for :title, "New booking equipment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New booking equipment</h1>

  <%= render "form", booking_equipment: @booking_equipment %>

  <%= link_to "Back to booking equipment", booking_equipments_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/booking_equipments/show.html.erb
<% content_for :title, "Showing booking equipment" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing booking equipment</h1>

  <%= render @booking_equipment %>

  <%= link_to "Edit this booking equipment", edit_booking_equipment_path(@booking_equipment), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to booking equipment", booking_equipments_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this booking equipment", @booking_equipment, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>